apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arc-app-of-apps
  namespace: argocd
spec:
  generators:
  - clusters: 
      selector:
        matchLabels:
          vcluster: "true"
  template:
    metadata:
      name: "{{name}}-actions-runner-controller"
    spec:
      project: default
      source:
        repoURL: https://github.com/jordanthomas761/vcluster_runners
        chart: arc
        targetRevision: 0.23.3
        helm:
          parameters:
            - name: targetRevision
              value: 0.23.3
            - name: cluster.name
              value: "{{name}}"
            - name: cluster.server
              value: "{{server}}"
      destination:
        name: in-cluster
        namespace: actions-runner-system
      syncPolicy: # (6)
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true