{{- range .Values.repos }}
{{- $repo:= split "/" . }}
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ $repo._1 }}-autoscaler
  namespace: actions-runner-workers
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: {{ $repo._1 }}-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: PercentageRunnersBusy
    scaleUpThreshold: '0.75'
    scaleDownThreshold: '0.25'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'
{{- end -}}