apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      images:
      - repoURL: ghcr.io/actions-runner-controller/actions-runner-controller/actions-runner
        semverConstraint: ^v2.307.1-ubuntu-20.04-dcb64f0
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/jordanthomas761/vcluster_runners
      writeBranch: stage/local-runners-east-non-prod-runners
      helm:
        images:
          - Image: ghcr.io/actions-runner-controller/actions-runner-controller/actions-runner
            valuesFilePath: runners
    argoCDAppUpdates:
    - appName: local-runners-east-non-prod-runners
      appNamespace: argocd