apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-ignore
spec:

  ignoreDifferences:
  - group: "policies"
    kind: "ClusterPolicy"
    jsonPointers:
    - /metadata/argocd.argoproj.io/sync-options

  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true