{{ $targetRevision := .Values.targetRevision  }}
{{- range .Values.clusters }}
{{- $clusterName := (printf "%s-runners-%s-%s" .account .region .environment) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: vcluster-{{ $clusterName }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $clusterName }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: {{ $targetRevision }}
    helm:
      parameters:
      - name: syncer.extraArgs[0]
        value: "--tls-san={{ $clusterName }}.{{ $clusterName }}-vcluster"
      - name: distro
        value: "k8s"
      - name: connect
        value: "false"
      - name: repository-config
        value: ''
  destination:
      name: in-cluster
      namespace: vcluster-{{ $clusterName }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
{{- end -}}