apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: runners-app-of-apps
  namespace: argocd
spec:
  generators:
  - clusters: 
      selector:
        matchLabels:
          vcluster: "true"
  template:
    metadata:
      name: {{`"{{name}}-runners"`}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-demo:{{- if contains `{{name}}` "non" }}test{{- else -}}prod{{- end }}
    spec:
      project: default
      source:
        repoURL: https://github.com/jordanthomas761/vcluster_runners
        path: runners
        targetRevision: stage/{{`{{name}}`}}
      destination:
        server: {{`"{{server}}"`}}
        namespace: actions-runner-workers
      syncPolicy: 
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true