apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: arc-app-of-apps
  namespace: argocd
spec:
  generators:
  - clusters: 
      selector:
        matchLabels:
          vcluster: "true"
  template:
    metadata:
      name: {{`"{{name}}-runners-app-of-apps"`}}
    spec:
      project: default
      source:
        repoURL: https://github.com/jordanthomas761/vcluster_runners
        path: runners
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy: 
        automated:
          selfHeal: true
          prune: true