apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jordanthomas761/vcluster_runners
    path: cluster-policies
    targetRevision: HEAD
    helm:
      parameters:
        - name: syncPeriod
          value: 1m
  destination:
      name: in-cluster
      namespace: kyverno

  ignoreDifferences:
      - group: "policies"
        kind: "ClusterPolicy"
        jsonPointers:
        - /metadata/argocd.argoproj.io/sync-options

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - RespectIgnoreDifferences=true

