apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kargo
    helm:
      passCredentials: true
      parameters:
        - name: set[0]
          value: "api.adminAccount.password=admin"
        - name: set[1]
          value: "api.adminAccount.tokenSigningKey=iwishtowashmyirishwristwatch"
    repoURL: ghcr.io/akuity/kargo-charts
    targetRevision: 0.1.0
  destination:
      name: in-cluster
      namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true