apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 3.0.5
  destination:
      name: in-cluster
      namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true