apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-arc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: actions-runner-controller
    targetRevision: {{ .Values.targetRevision }}
    helm:
      parameters:
        - name: syncPeriod
          value: 1m
  destination:
      server: {{ .Values.cluster.server }}
      namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true