apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-arc-workers-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/jordanthomas761/vcluster_runners
    path: arc-workers-namespace
    targetRevision: HEAD
  destination:
      server: {{ .Values.cluster.server }}
      namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true