apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-arc-workers-namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    path: arc-workers-namespace
    targetRevision: HEAD
  destination:
      server: {{ .Values.cluster.server }}
      namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true